create table measure (
	CEInputID nvarchar(255) primary key,
	PrgID nvarchar(255) not null,
	ClaimYearQuarter CedarsYearQuarter not null,
	Sector nvarchar(255) not null,
	DeliveryType nvarchar(20) not null,
	BldgType nvarchar(255) not null,
	E3ClimateZone nvarchar(255) not null,
	E3GasSavProfile nvarchar(255) ,
	E3GasSector nvarchar(255) ,
	E3MeaElecEndUseShape nvarchar(255),
	E3TargetSector nvarchar(255),
	MeasAppType nvarchar(255) not null,
	MeasCode nvarchar(255),
	MeasDescription nvarchar(255) not null,
	MeasImpactType nvarchar(50) not null,
	FuelID nvarchar(50) ,
	MeasureID nvarchar(100),
	TechGroup nvarchar(50) ,
	TechType nvarchar(50) not null,
	UseCategory nvarchar(50) ,
	UseSubCategory nvarchar(50) not null,
	WaterUse nvarchar(50) ,
	PreDesc nvarchar(255),
	StdDesc nvarchar(255),
	SourceDesc nvarchar(100),
	Version nvarchar(50) ,
	NormUnit nvarchar(255) not null,
	NumUnits numeric not null,
	UnitkW1stBaseline numeric not null,
	UnitkWh1stBaseline numeric not null,
	UnitTherm1stBaseline numeric not null,
	UnitkW2ndBaseline numeric not null,
	UnitkWh2ndBaseline numeric not null,
	UnitTherm2ndBaseline numeric not null,
	UnitkWhIOUWater1stBaseline numeric,
	UnitkWhIOUWater2ndBaseline numeric,
	UnitMeaCost1stBaseline numeric not null,
	UnitMeaCost2ndBaseline numeric not null,
	UnitDirectInstallLab numeric,
	UnitDirectInstallMat numeric,
	UnitEndUserRebate numeric,
	UnitIncentiveToOthers numeric,
	NTG_ID nvarchar(50) NTG,
	NTGRkW numeric CedarsNumRange (0, 1.5] not null,
	NTGRkWh numeric CedarsNumRange (0, 1.5] not null,
	NTGRTherm numeric CedarsNumRange (0, 1.5] not null,
	NTGRCost numeric CedarsNumRange (0, 1.5] not null,
	EUL_ID nvarchar(100) EUL,
	EUL_Yrs numeric CedarsNumRange [0, 40] not null,
	RUL_ID nvarchar(100) EUL,
	RUL_Yrs numeric CedarsNumRange [0, 30] not null,
	GSIA_ID nvarchar(50) GSIA,
	RealizationRatekW numeric CedarsNumRange (0, 2] not null,
	RealizationRatekWh numeric CedarsNumRange (0, 2] not null,
	RealizationRateTherm numeric CedarsNumRange (0, 2] not null,
	InstallationRatekW numeric CedarsNumRange (0, 1] not null,
	InstallationRatekWh numeric CedarsNumRange (0, 1] not null,
	InstallationRateTherm numeric CedarsNumRange (0, 1] not null,
	Residential_Flag boolean DefaultFalse,
	Upstream_Flag boolean DefaultFalse,
	IOU_AC_Territory nvarchar(255) check (IOU_AC_Territory in ('PGE', 'SDGE', 'SCE', 'SCG')) not null,
	UnitGasInfraBens numeric not null,
	UnitRefrigCosts numeric not null,
	UnitRefrigBens numeric not null,
	UnitMiscCosts numeric not null,
	MiscCostsDesc nvarchar(255),
	UnitMiscBens numeric not null,
	MiscBensDesc nvarchar(255),
	UnitTaxCredits numeric,
	RateScheduleElec nvarchar(255),
	RateScheduleGas nvarchar(255),
	CombustionType nvarchar(255),
	MeasInflation numeric CedarsNumRange [0, 1],
	Comments nvarchar(255));