create table measure (
	ceinputid nvarchar(255) primary key,
	prgid nvarchar(255) not null,
	claimyearquarter not null,
	sector nvarchar(255) not null,
	deliverytype nvarchar(20) not null,
	bldgtype nvarchar(255) not null,
	e3climatezone nvarchar(255) not null,
	e3gassavprofile nvarchar(255),
	e3gassector nvarchar(255),
	e3meaelecenduseshape nvarchar(255),
	e3targetsector nvarchar(255),
	measapptype nvarchar(255) not null,
	meascode nvarchar(255),
	measdescription nvarchar(255) not null,
	measimpacttype nvarchar(50) not null,
	fuelid nvarchar(50),
	measureid nvarchar(100),
	techgroup nvarchar(50),
	techtype nvarchar(50) not null,
	usecategory nvarchar(50),
	usesubcategory nvarchar(50) not null,
	wateruse nvarchar(50),
	predesc nvarchar(255),
	stddesc nvarchar(255),
	sourcedesc nvarchar(100),
	version nvarchar(50),
	normunit nvarchar(255) not null,
	numunits numeric not null,
	unitkw1stbaseline numeric not null,
	unitkwh1stbaseline numeric not null,
	unittherm1stbaseline numeric not null,
	unitkw2ndbaseline numeric not null,
	unitkwh2ndbaseline numeric not null,
	unittherm2ndbaseline numeric not null,
	unitkwhiouwater1stbaseline numeric,
	unitkwhiouwater2ndbaseline numeric,
	unitmeacost1stbaseline numeric not null,
	unitmeacost2ndbaseline numeric 0 not null,
	unitdirectinstalllab numeric,
	unitdirectinstallmat numeric,
	unitenduserrebate numeric,
	unitincentivetoothers numeric,
	ntg_id nvarchar(50),
	ntgrkw numeric check (ntgrkw > 0 and ntgrkw <= 1.5) not null,
	ntgrkwh numeric check (ntgrkwh > 0 and ntgrkwh <= 1.5) not null,
	ntgrtherm numeric check (ntgrtherm > 0 and ntgrtherm <= 1.5) not null,
	ntgrcost numeric check (ntgrcost > 0 and ntgrcost <= 1.5) not null,
	eul_id nvarchar(100),
	eul_yrs numeric check (eul_yrs >= 0 and eul_yrs <= 40) not null,
	rul_id nvarchar(100),
	rul_yrs numeric check (rul_yrs >= 0 and rul_yrs <= 30) not null,
	gsia_id nvarchar(50) gsia,
	realizationratekw numeric check (realizationratekw > 0 and realizationratekw <= 2) not null,
	realizationratekwh numeric check (realizationratekwh > 0 and realizationratekwh <= 2) not null,
	realizationratetherm numeric check (realizationratetherm > 0 and realizationratetherm <= 2) not null,
	installationratekw numeric check (installationratekw > 0 and installationratekw <= 1) not null,
	installationratekwh numeric check (installationratekwh > 0 and installationratekwh <= 1) not null,
	installationratetherm numeric check (installationratetherm > 0 and installationratetherm <= 1) not null,
	residential_flag bit,
	upstream_flag bit,
	iou_ac_territory nvarchar(255) not null,
	unitgasinfrabens numeric not null,
	unitrefrigcosts numeric not null,
	unitrefrigbens numeric not null,
	unitmisccosts numeric not null,
	misccostsdesc nvarchar(255),
	unitmiscbens numeric not null,
	miscbensdesc nvarchar(255),
	unittaxcredits numeric,
	ratescheduleelec nvarchar(255),
	rateschedulegas nvarchar(255),
	combustiontype nvarchar(255),
	measinflation numeric check (measinflation >= 0 and measinflation <= 1),
	comments nvarchar(255)
);